#[rustfmt::skip]
const KEY_MAP: [InputEvent; u8::MAX as usize] = [
    InputEvent::Key { ctrl: true,  key: '@' },
    InputEvent::Key { ctrl: true,  key: 'a' },
    InputEvent::Key { ctrl: true,  key: 'b' },
    InputEvent::Key { ctrl: true,  key: 'c' },
    InputEvent::Key { ctrl: true,  key: 'd' },
    InputEvent::Key { ctrl: true,  key: 'e' },
    InputEvent::Key { ctrl: true,  key: 'f' },
    InputEvent::Key { ctrl: true,  key: 'g' },
    InputEvent::Key { ctrl: true,  key: 'h' },
    InputEvent::Key { ctrl: false, key: '\t'},
    InputEvent::Key { ctrl: true,  key: 'j' },
    InputEvent::Key { ctrl: true,  key: 'k' },
    InputEvent::Key { ctrl: true,  key: 'l' },
    InputEvent::Enter,
    InputEvent::Key { ctrl: true,  key: 'n' },
    InputEvent::Key { ctrl: true,  key: 'o' },
    InputEvent::Key { ctrl: true,  key: 'p' },
    InputEvent::Key { ctrl: true,  key: 'q' },
    InputEvent::Key { ctrl: true,  key: 'r' },
    InputEvent::Key { ctrl: true,  key: 's' },
    InputEvent::Key { ctrl: true,  key: 't' },
    InputEvent::Key { ctrl: true,  key: 'u' },
    InputEvent::Key { ctrl: true,  key: 'v' },
    InputEvent::Key { ctrl: true,  key: 'w' },
    InputEvent::Key { ctrl: true,  key: 'x' },
    InputEvent::Key { ctrl: true,  key: 'y' },
    InputEvent::Key { ctrl: true,  key: 'z' },
    InputEvent::Esc,
    InputEvent::Cancel,
    InputEvent::GroupSeparator,
    InputEvent::None,
    InputEvent::None,
    InputEvent::Key { ctrl: false, key: ' ' },
    InputEvent::Key { ctrl: false, key: '!' },
    InputEvent::Key { ctrl: false, key: '"' },
    InputEvent::Key { ctrl: false, key: '#' },
    InputEvent::Key { ctrl: false, key: '$' },
    InputEvent::Key { ctrl: false, key: '%' },
    InputEvent::Key { ctrl: false, key: '&' },
    InputEvent::Key { ctrl: false, key: '\''},
    InputEvent::Key { ctrl: false, key: '(' },
    InputEvent::Key { ctrl: false, key: ')' },
    InputEvent::Key { ctrl: false, key: '*' },
    InputEvent::Key { ctrl: false, key: '+' },
    InputEvent::Key { ctrl: false, key: ',' },
    InputEvent::Key { ctrl: false, key: '-' },
    InputEvent::Key { ctrl: false, key: '.' },
    InputEvent::Key { ctrl: false, key: '/' },
    InputEvent::Key { ctrl: false, key: '0' },
    InputEvent::Key { ctrl: false, key: '1' },
    InputEvent::Key { ctrl: false, key: '2' },
    InputEvent::Key { ctrl: false, key: '3' },
    InputEvent::Key { ctrl: false, key: '4' },
    InputEvent::Key { ctrl: false, key: '5' },
    InputEvent::Key { ctrl: false, key: '6' },
    InputEvent::Key { ctrl: false, key: '7' },
    InputEvent::Key { ctrl: false, key: '8' },
    InputEvent::Key { ctrl: false, key: '9' },
    InputEvent::Key { ctrl: false, key: '<' },
    InputEvent::Key { ctrl: false, key: ';' },
    InputEvent::Key { ctrl: false, key: '>' },
    InputEvent::Key { ctrl: false, key: '=' },
    InputEvent::None,
    InputEvent::Key { ctrl: false, key: '?' },
    InputEvent::Key { ctrl: false, key: '@' },
    InputEvent::Key { ctrl: false, key: 'A' },
    InputEvent::Key { ctrl: false, key: 'B' },
    InputEvent::Key { ctrl: false, key: 'C' },
    InputEvent::Key { ctrl: false, key: 'D' },
    InputEvent::Key { ctrl: false, key: 'E' },
    InputEvent::Key { ctrl: false, key: 'F' },
    InputEvent::Key { ctrl: false, key: 'G' },
    InputEvent::Key { ctrl: false, key: 'H' },
    InputEvent::Key { ctrl: false, key: 'I' },
    InputEvent::Key { ctrl: false, key: 'J' },
    InputEvent::Key { ctrl: false, key: 'K' },
    InputEvent::Key { ctrl: false, key: 'L' },
    InputEvent::Key { ctrl: false, key: 'M' },
    InputEvent::Key { ctrl: false, key: 'N' },
    InputEvent::Key { ctrl: false, key: 'O' },
    InputEvent::Key { ctrl: false, key: 'P' },
    InputEvent::Key { ctrl: false, key: 'Q' },
    InputEvent::Key { ctrl: false, key: 'R' },
    InputEvent::Key { ctrl: false, key: 'S' },
    InputEvent::Key { ctrl: false, key: 'T' },
    InputEvent::Key { ctrl: false, key: 'U' },
    InputEvent::Key { ctrl: false, key: 'V' },
    InputEvent::Key { ctrl: false, key: 'W' },
    InputEvent::Key { ctrl: false, key: 'X' },
    InputEvent::Key { ctrl: false, key: 'Y' },
    InputEvent::Key { ctrl: false, key: 'Z' },
    InputEvent::Key { ctrl: false, key: '[' },
    InputEvent::Key { ctrl: false, key: '\\'},
    InputEvent::Key { ctrl: false, key: ']' },
    InputEvent::Key { ctrl: false, key: '^' },
    InputEvent::Key { ctrl: false, key: '_' },
    InputEvent::Key { ctrl: false, key: '`' },
    InputEvent::Key { ctrl: false, key: 'a' },
    InputEvent::Key { ctrl: false, key: 'b' },
    InputEvent::Key { ctrl: false, key: 'c' },
    InputEvent::Key { ctrl: false, key: 'd' },
    InputEvent::Key { ctrl: false, key: 'e' },
    InputEvent::Key { ctrl: false, key: 'f' },
    InputEvent::Key { ctrl: false, key: 'g' },
    InputEvent::Key { ctrl: false, key: 'h' },
    InputEvent::Key { ctrl: false, key: 'i' },
    InputEvent::Key { ctrl: false, key: 'j' },
    InputEvent::Key { ctrl: false, key: 'k' },
    InputEvent::Key { ctrl: false, key: 'l' },
    InputEvent::Key { ctrl: false, key: 'm' },
    InputEvent::Key { ctrl: false, key: 'n' },
    InputEvent::Key { ctrl: false, key: 'o' },
    InputEvent::Key { ctrl: false, key: 'p' },
    InputEvent::Key { ctrl: false, key: 'q' },
    InputEvent::Key { ctrl: false, key: 'r' },
    InputEvent::Key { ctrl: false, key: 's' },
    InputEvent::Key { ctrl: false, key: 't' },
    InputEvent::Key { ctrl: false, key: 'u' },
    InputEvent::Key { ctrl: false, key: 'v' },
    InputEvent::Key { ctrl: false, key: 'w' },
    InputEvent::Key { ctrl: false, key: 'x' },
    InputEvent::Key { ctrl: false, key: 'y' },
    InputEvent::Key { ctrl: false, key: 'z' },
    InputEvent::Key { ctrl: false, key: '{' },
    InputEvent::Key { ctrl: false, key: '|' },
    InputEvent::Key { ctrl: false, key: '}' },
    InputEvent::Key { ctrl: false, key: '~' },
    InputEvent::Backspace,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
    InputEvent::None,
];

#[derive(Debug)]
pub enum InputEvent {
    Cancel,
    Backspace,
    Enter,
    Esc,
    GroupSeparator,
    Key { ctrl: bool, key: char },
    Mouse,
    None,
    Raw(u8),
}

impl InputEvent {
    pub const fn from_raw(raw: u8) -> &'static Self {
        &KEY_MAP[raw as usize]
    }
    pub fn is_none(&self) -> bool {
        match self {
            Self::None => true,
            _ => false,
        }
    }
    pub fn is_some(&self) -> bool {
        match self {
            Self::None => false,
            _ => true,
        }
    }
}
