use crate::components::CharEntry;
use crate::point::Vec2;
use std::{collections::HashSet, sync::Arc};

type IoResult<T> = std::io::Result<T>;

#[derive(Debug)]
pub enum TerminalRequestParseErr {}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum TerminalRequest {
    Reset,
    Bold,
    Shadow,
    Dim,
    Italic,
    Underline,
    NoUnderline,
    SingleUnderline,
    DoubleUnderline,
    CurlyUnderline,
    DottedUnderline,
    DashedUnderline,
    SlowBlink,
    RapidBlink,
    ReverseVideo,
    Conceal,
    Overstrike,
    StrikeThrough,
    DefaultFont,
    AlternateFont1,
    AlternateFont2,
    AlternateFont3,
    AlternateFont4,
    AlternateFont5,
    AlternateFont6,
    AlternateFont7,
    AlternateFont8,
    AlternateFont9,
    AlternateFont10,
    ResetBoldOrDim,
    ResetItalicOrAlternateFont,
    ResetUnderline,
    ResetBlink,
    ResetReversedVideo,
    ResetConcealOrOverstrike,
    ResetStrikeThrough,
    BlackForeground,
    RedForeground,
    GreenForeground,
    YellowForeground,
    BlueForeground,
    MagentaForeground,
    CyanForeground,
    WhiteForeground,
    SetForegroundColor24BitTrueColor { r: u8, g: u8, b: u8 },
    SetForegroundColor256ColorPalette { n: u8 },
    DefaultForegroundColor,
    BlackBackground,
    RedBackground,
    GreenBackground,
    YellowBackground,
    BlueBackground,
    MagentaBackground,
    CyanBackground,
    WhiteBackground,
    SetBackgroundColor24BitTrueColor { r: u8, g: u8, b: u8 },
    SetBackgroundColor256ColorPalette { n: u8 },
    DefaultBackgroundColor,
    Frame,
    Encircle,
    Overline,
    ResetFrameOrEncircle,
    ResetOverline,
    SetUnderlineColor24BitTrueColor { r: u8, g: u8, b: u8 },
    SetUnderlineColor256ColorPalette { n: u8 },
    ResetUnderlineColor,
    Superscript,
    Subscript,
    ResetSuperOrSubscript,
    BrightBlackForeground,
    BrightRedForeground,
    BrightGreenForeground,
    BrightYellowForeground,
    BrightBlueForeground,
    BrightMagentaForeground,
    BrightCyanForeground,
    BrightWhiteForeground,
    BrightBlackBackground,
    BrightRedBackground,
    BrightGreenBackground,
    BrightYellowBackground,
    BrightBlueBackground,
    BrightMagentaBackground,
    BrightCyanBackground,
    BrightWhiteBackground,
    ScrollLeft { cols: u8 },
    ScrollRight { cols: u8 },
    GraphicSizeModification { h: u8, w: u8 },
    FontSelection { font: String, id: u8 },
    JustifyEndJustification,
    JustifyWordFill,
    JustifyInterwordSpace,
    JustifyLetterSpace,
    JustifyHyphenation,
    JustifyFlushLeft,
    JustifyCenter,
    JustifyFlushRight,
    JustifyitalianHyphenation,
    QuadFlushLeft,
    QuadFlushLeftWithLeader,
    QuadCenter,
    QuadCenterWithLeader,
    QuadFlushRight,
    QuadFlushRightWithLeader,
    // SelectSizeUnitInternationalTypographicStandard,
    // SelectSizeUnitDecipoint,
    // SelectSizeUnitDidot,
    // SelectSizeUnitMil,
    // SelectSizeUnitMetric,
    GraphicSizeSelection { height: u8 },
    SpacingIncrement { interline: u8, space: u8 },
    ThinSpaceSpecification { width: u8 },
    SetCursorStyle { style: String },
    SetWarningBellVolume,
    SetMarginBellVolume,
    SoftTerminalReset,
    SelectConformanceLevel { level: u8, mode: u8 },
    SelectCharProtectionAttribute { attr: u8 },
    InsertCharacters { n: u8 },
    // HorizontalCursorPosAbsolute,
    RequestaNSIMode,
    ChangeAttributesInRectangularArea,
    ReverseAttributesInRectangularArea,
    CopyRectangularArea,
    FillRectangularArea,
    EraseRectangularArea,
    HorizontalCursorPosRelative { cols: u8 },
    MoveCursorUp { rows: u8 },
    RepeatCharacter { n: u8 },
    MoveCursorDown { rows: u8 },
    DeviceAttributesRequestPrimaryDeviceAttrs,
    DeviceAttributesRequestSecondaryDeviceAttrs,
    MoveCursorForward { cols: u8 },
    VerticalCursorPosAbsolute { row: u8 },
    MoveCursorBack { cols: u8 },
    VerticalCursorPosRelative { rows: u8 },
    MoveCursorToNextLine { rows: u8 },
    HorizontalVerticalCursorPos { row: u8, col: u8 },
    MoveCursorToPreviousLine { rows: u8 },
    TabClearClearCurrentColumn,
    TabClearClearAllTabs,
    MoveCursorCharAbsolute { col: u8 },
    // SetModeInsertMode,
    // SetModeAutomaticNewline,
    MoveCursorPos { row: i16, col: i16 },
    MediaCopyPrintScreen,
    MediaCopyPrinterModeOff,
    MediaCopyPrinterModeOn,
    MoveCursorHorizontalTabulation { n: u8 },
    HorizontalPosBackward { cols: u8 },
    EraseFromCursorToEndOfScreen,
    EraseFromCursorToBeginningOfScreen,
    EraseEntireScreen,
    EraseEntireScreenAndClearScrollbackBuffer,
    VerticalPosBackward { rows: u8 },
    EraseFromCursorToEndOfLine,
    EraseFromCursorToBeginningOfLine,
    EraseEntireLine,
    // ResetModeReplaceMode,
    // ResetModeNormalLinefeed,
    InsertLines { n: u8 },
    SelectGraphicRendition,
    DeleteLines { n: u8 },
    DeviceStatusReportReady,
    DeviceStatusReportStatusReport,
    DeviceStatusReportReportCursorPos,
    DeviceStatusReportReportCursorPosResponse,
    EraseInFieldFromCursorToEndOfField,
    EraseInFieldFromBeginningOfFieldToCursor,
    EraseInFieldEntireField,
    // DefineAreaQualificationUnprotected,
    // DefineAreaQualificationGuarded,
    // DefineAreaQualificationGraphicCharInput,
    // DefineAreaQualificationNumericInput,
    // DefineAreaQualificationAlphabeticInput,
    // DefineAreaQualificationInputJustifiedRight,
    // DefineAreaQualificationFillWithZeros,
    // DefineAreaQualificationSetHorizontalTab,
    // DefineAreaQualificationProtected,
    // DefineAreaQualificationFillWithSpaces,
    EraseInAreaFromCursorToEndOfArea,
    EraseInAreaFromBeginningOfAreaToCursor,
    EraseInAreaEntireArea,
    DeleteCharacters { n: u8 },
    LoadlEDsTurnOffAlllEDs,
    LoadlEDsTurnOnlED1,
    LoadlEDsTurnOnlED2,
    LoadlEDsTurnOnlED3,
    LoadlEDsTurnOnlED4,
    SelectEditingExtentEntireBuffer,
    SelectEditingExtentActiveLine,
    SelectEditingExtentBetweenHorizontalTabs,
    SelectEditingExtentQualifiedArea,
    SetScrollingRegion { top: u8, bottom: u8 },
    CursorPosReport { row: u8, col: u8 },
    SaveCursorPos,
    // ScrollUp,
    WindowManipulation,
    // ScrollDown,
    RestoreCursorPos,
    NextPage { n: u8 },
    PrecedingPage { n: u8 },
    CursorTabControlSetHorizontalTabAtActivePos,
    CursorTabControlSetVerticalTabAtActiveLine,
    CursorTabControlClearHorizontalTabAtActivePos,
    CursorTabControlClearVerticalTabAtActiveLine,
    CursorTabControlClearAllHorizontalTabsAtActiveLine,
    CursorTabControlClearAllHorizontalTabs,
    CursorTabControlClearAllVerticalTabs,
    RequestTerminalParameters,
    EraseCharacters { n: u8 },
    TestDiagnosticData,
    CursorVerticalTabulation { n: u8 },
    CursorBackwardTabulation { n: u8 },
    EnableCursorKeyToApplication,
    DisableCursorKeyToApplication,
    EnableaNSIMode,
    DisableaNSIMode,
    EnableNumberOfColumnsTo132,
    DisableNumberOfColumnsTo132,
    EnableSmoothScrolling,
    DisableSmoothScrolling,
    EnableScreenModeToReverseVideo,
    DisableScreenModeToReverseVideo,
    EnableOriginModeToRelative,
    DisableOriginModeToRelative,
    EnableAutoWrapMode,
    DisableAutoWrapMode,
    EnableAutoRepeatKeys,
    DisableAutoRepeatKeys,
    EnableInterlaceMode,
    DisableInterlaceMode,
    EnableShowToolbar,
    DisableShowToolbar,
    EnableBlinkingCursor,
    DisableBlinkingCursor,
    EnablePrintFeedForm,
    DisablePrintFeedForm,
    EnablePrintExtent,
    DisablePrintExtent,
    EnableShowCursor,
    DisableShowCursor,
    EnableShowScrollbar,
    DisableShowScrollbar,
    EnableEnableFontShifting,
    DisableEnableFontShifting,
    EnableEntertektronixMode,
    DisableEntertektronixMode,
    // EnableAllow80,
    // DisableAllow80,
    // EnableMore,
    // DisableMore,
    EnableNationalOrMultinationalCharMode,
    DisableNationalOrMultinationalCharMode,
    EnableMarginBell,
    DisableMarginBell,
    EnableReverseWraparoundMode,
    DisableReverseWraparoundMode,
    EnableStartLogging,
    DisableStartLogging,
    EnableAlternateScreenBuffer,
    DisableAlternateScreenBuffer,
    EnableAlternateScreenBufferCursorSaveOrRestore,
    DisableAlternateScreenBufferCursorSaveOrRestore,
    EnableApplicationKeypadMode,
    DisableApplicationKeypadMode,
    EnableBackarrowSendsBackspace,
    DisableBackarrowSendsBackspace,
    EnableVerticalSplitScreenMode,
    DisableVerticalSplitScreenMode,
    // EnableDon,
    // DisableDon,
    EnablevT200MouseReporting,
    DisablevT200MouseReporting,
    Enablex11MouseReporting,
    Disablex11MouseReporting,
    EnableButtonEventMouseReporting,
    DisableButtonEventMouseReporting,
    EnableAnyEventMouseReporting,
    DisableAnyEventMouseReporting,
    EnableFocusInOrOutEvents,
    DisableFocusInOrOutEvents,
    EnableuTF8MouseMode,
    DisableuTF8MouseMode,
    EnablesGRMouseMode,
    DisablesGRMouseMode,
    EnableAlternateScrollMode,
    DisableAlternateScrollMode,
    EnableScrollToBottomOnTtyOutput,
    DisableScrollToBottomOnTtyOutput,
    EnableScrollToBottomOnKeypress,
    DisableScrollToBottomOnKeypress,
    EnableUsecLIPBOARDForSpecialPaste,
    DisableUsecLIPBOARDForSpecialPaste,
    EnableUrxvtMouseMode,
    DisableUrxvtMouseMode,
    // EnablesGRMousePixelMode,
    // DisablesGRMousePixelMode,
    EnableBoldKeySendsdEL,
    DisableBoldKeySendsdEL,
    EnablesunFunctionKeyMode,
    DisablesunFunctionKeyMode,
    EnableMetaSendseSC,
    DisableMetaSendseSC,
    Enable8BitMetaKey,
    Disable8BitMetaKey,
    EnableNumericKeypadMetaKey,
    DisableNumericKeypadMetaKey,
    EnableAlternateKeyModifiers,
    DisableAlternateKeyModifiers,
    EnableDeleteKeyToSenddEL,
    DisableDeleteKeyToSenddEL,
    EnablealtKeyMode,
    DisablealtKeyMode,
    EnableAlternateBackspace,
    DisableAlternateBackspace,
    EnablealtSendseSCPrefix,
    DisablealtSendseSCPrefix,
    EnableKeepSelectionEvenIfNotHighlighted,
    DisableKeepSelectionEvenIfNotHighlighted,
    EnableUsecLIPBOARDSelection,
    DisableUsecLIPBOARDSelection,
    EnableBellToUrgent,
    DisableBellToUrgent,
    EnableEnableRaisingWindowOnbEL,
    DisableEnableRaisingWindowOnbEL,
    EnableReuseMostRecentDataTocLIPBOARD,
    DisableReuseMostRecentDataTocLIPBOARD,
    EnableExtendedReverseWraparoundMode,
    DisableExtendedReverseWraparoundMode,
    EnableApplicationCursorKeysMode,
    DisableApplicationCursorKeysMode,
    EnableAlternateScreenMode,
    DisableAlternateScreenMode,
    EnableExtendedCursorMode,
    DisableExtendedCursorMode,
    EnableTermcapOrTerminfoSpecialKeys,
    DisableTermcapOrTerminfoSpecialKeys,
    EnablesunFunctionKeys,
    DisablesunFunctionKeys,
    EnablehPFunctionKeys,
    DisablehPFunctionKeys,
    EnablesCOFunctionKeys,
    DisablesCOFunctionKeys,
    EnablevT200Highlighting,
    DisablevT200Highlighting,
    EnablevT220Highlighting,
    DisablevT220Highlighting,
    EnablevT320Highlighting,
    DisablevT320Highlighting,
    EnableLegacyXtermKeys,
    DisableLegacyXtermKeys,
    EnablevT220Keyboard,
    DisablevT220Keyboard,
    EnablevT220FunctionKeys,
    DisablevT220FunctionKeys,
    EnableSixKeyFunctionKeys,
    DisableSixKeyFunctionKeys,
    EnableBracketedPasteMode,
    DisableBracketedPasteMode,
    EnableSynchronizedOutputMode,
    DisableSynchronizedOutputMode,
    // PrivateSequence,
    SetWindowTitleAndIconName { text: String },
    SetIconName { text: String },
    SetWindowTitle { text: String },
    SetxPropertyOnTopLevelWindow,
    SetOrReadPaletteColor { n: u8, color_spec: String },
    ChangeSpecialColorSpec,
    EnableSpecialColor,
    SetCurrentWorkingDirectory { url: String },
    Hyperlink { params: String, url: String },
    // HyperlinkEnd,
    SetOrReadTextForegroundColor { color_spec: String },
    SetOrReadTextBackgroundColor { color_spec: String },
    SetOrReadTextCursorColor { color_spec: String },
    ChangeMouseForegroundColor,
    ChangeMouseBackgroundColor,
    ChangetektronixForegroundColor,
    ChangetektronixBackgroundColor,
    ChangeHighlightColor,
    ChangetektronixCursorColor,
    ChangeHighlightForegroundColor,
    SetLogFile,
    SetFont,
    ReservedForEmacsShell,
    ManipulateClipboard { c: String, data: String },
    ResetPaletteColor { n: u8 },
    ResetSpecialColorSpec,
    DisableSpecialColor,
    // ResetDynamicColor,
    // FinalTermShellIntegration,
    SendNotification { message: String },
    XtermModification { name: String, value: String },
    ITerm2ShellIntegration,
    Send7Bitc1Controls,
    Send8Bitc1Controls,
    SetaNSIConformanceLevel1,
    SetaNSIConformanceLevel2,
    SetaNSIConformanceLevel3,
    SetaNSIConformanceLevel4,
    // aPCString,
    // g0SelectSpecialGraphicsSet,
    // g0SelectAlternaterOMStandardCharSet,
    // g0SelectAlternaterOMSpecialGraphicsSet,
    // g0SelectuKCharSet,
    // g0SelectaSCIICharSet,
    // g1SelectSpecialGraphicsSet,
    // g1SelectAlternaterOMStandardCharSet,
    // g1SelectAlternaterOMSpecialGraphicsSet,
    // g1SelectuKCharSet,
    // g1SelectaSCIICharSet,
    ControlSequenceIntroducer,
    OperatingSystemCommand,
    Invokeg2CharSetAsgR,
    // g2SelectSpecialGraphicsSet,
    // g2SelectAlternaterOMStandardCharSet,
    // g2SelectAlternaterOMSpecialGraphicsSet,
    // g2SelectuKCharSet,
    // g2SelectaSCIICharSet,
    StringTerminator,
    // DoubleHeightLine,
    // SingleWidth,
    // DoubleWidth,
    ScreenAlignmentPattern,
    SelectDefaultCharSet,
    SelectuTF8CharSet,
    StartOfString,
    // g3SelectSpecialGraphicsSet,
    // g3SelectAlternaterOMStandardCharSet,
    // g3SelectAlternaterOMSpecialGraphicsSet,
    // g3SelectuKCharSet,
    // g3SelectaSCIICharSet,
    // vT52Mode,
    ApplicationKeypad,
    NormalKeypad,
    Invokeg1CharSetAsgR,
    BackIndex,
    ForwardIndex,
    ResetToInitialState,
    Index,
    NextLine,
    HorizontalTabSet,
    VerticalTabSet,
    MemoryLock,
    ReverseIndex,
    Invokeg2CharSet,
    SingleShift2,
    Invokeg3CharSet,
    SingleShift3,
    DeviceControlString,
    // PrivacyMessage,
    // IdentifyDevice,
    // DownloadableCharSetDefinition,
    // SetTermcapOrTerminfoData,
    // RequestTermcapOrTerminfoString,
    // dECUDK,
    // dECRQSSRequest,
    // RequestSelectionOrSetting,
    // RestorePresentationState,
    // RestoreFormatState,
    // ApplicationProgramCommand,
}

impl std::fmt::Display for TerminalRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        use TerminalRequest::*;
        match self {
            // ClearScreen => write!(f, "[3J"),
            // EnterAltScreen => write!(f, "[?47h"),
            // ExitAltScreen => write!(f, "[?47l"),
            Reset => write!(f, "[0m"),
            Bold => write!(f, "[1m"),
            Shadow => write!(f, "[1:2m"),
            Dim => write!(f, "[2m"),
            Italic => write!(f, "[3m"),
            Underline => write!(f, "[4m"),
            NoUnderline => write!(f, "[4:0m"),
            SingleUnderline => write!(f, "[4:1m"),
            DoubleUnderline => write!(f, "[4:2m"),
            CurlyUnderline => write!(f, "[4:3m"),
            DottedUnderline => write!(f, "[4:4m"),
            DashedUnderline => write!(f, "[4:5m"),
            SlowBlink => write!(f, "[5m"),
            RapidBlink => write!(f, "[6m"),
            ReverseVideo => write!(f, "[7m"),
            Conceal => write!(f, "[8m"),
            Overstrike => write!(f, "[8:7m"),
            StrikeThrough => write!(f, "[9m"),
            DefaultFont => write!(f, "[10m"),
            AlternateFont1 => write!(f, "[11m"),
            AlternateFont2 => write!(f, "[12m"),
            AlternateFont3 => write!(f, "[13m"),
            AlternateFont4 => write!(f, "[14m"),
            AlternateFont5 => write!(f, "[15m"),
            AlternateFont6 => write!(f, "[16m"),
            AlternateFont7 => write!(f, "[17m"),
            AlternateFont8 => write!(f, "[18m"),
            AlternateFont9 => write!(f, "[19m"),
            AlternateFont10 => write!(f, "[20m"),
            ResetBoldOrDim => write!(f, "[22m"),
            ResetItalicOrAlternateFont => write!(f, "[23m"),
            ResetUnderline => write!(f, "[24m"),
            ResetBlink => write!(f, "[25m"),
            ResetReversedVideo => write!(f, "[27m"),
            ResetConcealOrOverstrike => write!(f, "[28m"),
            ResetStrikeThrough => write!(f, "[29m"),
            BlackForeground => write!(f, "[30m"),
            RedForeground => write!(f, "[31m"),
            GreenForeground => write!(f, "[32m"),
            YellowForeground => write!(f, "[33m"),
            BlueForeground => write!(f, "[34m"),
            MagentaForeground => write!(f, "[35m"),
            CyanForeground => write!(f, "[36m"),
            WhiteForeground => write!(f, "[37m"),
            SetForegroundColor24BitTrueColor { r, g, b } => write!(f, "[38;2;{};{};{}m", r, g, b),
            SetForegroundColor256ColorPalette { n } => write!(f, "[38;5;{}m", n),
            DefaultForegroundColor => write!(f, "[39m"),
            BlackBackground => write!(f, "[40m"),
            RedBackground => write!(f, "[41m"),
            GreenBackground => write!(f, "[42m"),
            YellowBackground => write!(f, "[43m"),
            BlueBackground => write!(f, "[44m"),
            MagentaBackground => write!(f, "[45m"),
            CyanBackground => write!(f, "[46m"),
            WhiteBackground => write!(f, "[47m"),
            SetBackgroundColor24BitTrueColor { r, g, b } => write!(f, "[48;2;{};{};{}m", r, g, b),
            SetBackgroundColor256ColorPalette { n } => write!(f, "[48;5;{}m", n),
            DefaultBackgroundColor => write!(f, "[49m"),
            Frame => write!(f, "[51m"),
            Encircle => write!(f, "[52m"),
            Overline => write!(f, "[53m"),
            ResetFrameOrEncircle => write!(f, "[54m"),
            ResetOverline => write!(f, "[55m"),
            SetUnderlineColor24BitTrueColor { r, g, b } => write!(f, "[58;2;{};{};{}m", r, g, b),
            SetUnderlineColor256ColorPalette { n } => write!(f, "[58;5;{}m", n),
            ResetUnderlineColor => write!(f, "[59m"),
            Superscript => write!(f, "[73m"),
            Subscript => write!(f, "[74m"),
            ResetSuperOrSubscript => write!(f, "[75m"),
            BrightBlackForeground => write!(f, "[90m"),
            BrightRedForeground => write!(f, "[91m"),
            BrightGreenForeground => write!(f, "[92m"),
            BrightYellowForeground => write!(f, "[93m"),
            BrightBlueForeground => write!(f, "[94m"),
            BrightMagentaForeground => write!(f, "[95m"),
            BrightCyanForeground => write!(f, "[96m"),
            BrightWhiteForeground => write!(f, "[97m"),
            BrightBlackBackground => write!(f, "[100m"),
            BrightRedBackground => write!(f, "[101m"),
            BrightGreenBackground => write!(f, "[102m"),
            BrightYellowBackground => write!(f, "[103m"),
            BrightBlueBackground => write!(f, "[104m"),
            BrightMagentaBackground => write!(f, "[105m"),
            BrightCyanBackground => write!(f, "[106m"),
            BrightWhiteBackground => write!(f, "[107m"),
            ScrollLeft { cols } => write!(f, "[{} @", cols),
            ScrollRight { cols } => write!(f, "[{} A", cols),
            GraphicSizeModification { h, w } => write!(f, "[{};{} B", h, w),
            FontSelection { font, id } => write!(f, "[{};{} D", font, id),
            JustifyEndJustification => write!(f, "[0 F"),
            JustifyWordFill => write!(f, "[1 F"),
            JustifyInterwordSpace => write!(f, "[2 F"),
            JustifyLetterSpace => write!(f, "[3 F"),
            JustifyHyphenation => write!(f, "[4 F"),
            JustifyFlushLeft => write!(f, "[5 F"),
            JustifyCenter => write!(f, "[6 F"),
            JustifyFlushRight => write!(f, "[7 F"),
            JustifyitalianHyphenation => write!(f, "[8 F"),
            QuadFlushLeft => write!(f, "[0 H"),
            QuadFlushLeftWithLeader => write!(f, "[1 H"),
            QuadCenter => write!(f, "[2 H"),
            QuadCenterWithLeader => write!(f, "[3 H"),
            QuadFlushRight => write!(f, "[4 H"),
            QuadFlushRightWithLeader => write!(f, "[5 H"),
            // SelectSizeUnitInternationalTypographicStandard => write!(f, "[1 I"),
            // SelectSizeUnitDecipoint_1_OR_720_INCH => write!(f, "[2 I"),
            // SelectSizeUnitDidot => write!(f, "[3 I"),
            // SelectSizeUnitMil_1_OR_1000_INCH => write!(f, "[4 I"),
            // SelectSizeUnitMetric_0_01_MM => write!(f, "[5 I"),
            GraphicSizeSelection { height } => write!(f, "[{} J", height),
            SpacingIncrement { interline, space } => write!(f, "[{};{} K", interline, space),
            ThinSpaceSpecification { width } => write!(f, "[{} L", width),
            SetCursorStyle { style } => write!(f, "[{} q", style),
            SetWarningBellVolume => write!(f, "[ t"),
            SetMarginBellVolume => write!(f, "[ u"),
            SoftTerminalReset => write!(f, "[!p"),
            SelectConformanceLevel { level, mode } => write!(f, "[{};{}\"p", level, mode),
            SelectCharProtectionAttribute { attr } => write!(f, "[{}\"q", attr),
            InsertCharacters { n } => write!(f, "[{}@", n),
            // HorizontalCursorPosAbsolute => write!(f,"[<col" `),
            RequestaNSIMode => write!(f, "[$p"),
            ChangeAttributesInRectangularArea => write!(f, "[$r"),
            ReverseAttributesInRectangularArea => write!(f, "[$t"),
            CopyRectangularArea => write!(f, "[$v"),
            FillRectangularArea => write!(f, "[$x"),
            EraseRectangularArea => write!(f, "[$z"),
            HorizontalCursorPosRelative { cols } => write!(f, "[{}a", cols),
            MoveCursorUp { rows } => write!(f, "[{}A", rows),
            RepeatCharacter { n } => write!(f, "[{}b", n),
            MoveCursorDown { rows } => write!(f, "[{}B", rows),
            DeviceAttributesRequestPrimaryDeviceAttrs => write!(f, "[0c"),
            DeviceAttributesRequestSecondaryDeviceAttrs => write!(f, "[>0c"),
            MoveCursorForward { cols } => write!(f, "[{}C", cols),
            VerticalCursorPosAbsolute { row } => write!(f, "[{}d", row),
            MoveCursorBack { cols } => write!(f, "[{}D", cols),
            VerticalCursorPosRelative { rows } => write!(f, "[{}e", rows),
            MoveCursorToNextLine { rows } => write!(f, "[{}E", rows),
            HorizontalVerticalCursorPos { row, col } => write!(f, "[{};{}f", row, col),
            MoveCursorToPreviousLine { rows } => write!(f, "[{}F", rows),
            TabClearClearCurrentColumn => write!(f, "[0g"),
            TabClearClearAllTabs => write!(f, "[3g"),
            MoveCursorCharAbsolute { col } => write!(f, "[{}G", col),
            // SetModeInsertMode_irm => write!(f, "[4h"),
            // SetModeAutomaticNewline_lnm => write!(f, "[20h"),
            MoveCursorPos { row, col } => write!(f, "[{};{}H", row, col),
            MediaCopyPrintScreen => write!(f, "[0i"),
            MediaCopyPrinterModeOff => write!(f, "[4i"),
            MediaCopyPrinterModeOn => write!(f, "[5i"),
            MoveCursorHorizontalTabulation { n } => write!(f, "[{}I", n),
            HorizontalPosBackward { cols } => write!(f, "[{}j", cols),
            EraseFromCursorToEndOfScreen => write!(f, "[0J"),
            EraseFromCursorToBeginningOfScreen => write!(f, "[1J"),
            EraseEntireScreen => write!(f, "[2J"),
            EraseEntireScreenAndClearScrollbackBuffer => write!(f, "[3J"),
            VerticalPosBackward { rows } => write!(f, "[{}k", rows),
            EraseFromCursorToEndOfLine => write!(f, "[0K"),
            EraseFromCursorToBeginningOfLine => write!(f, "[1K"),
            EraseEntireLine => write!(f, "[2K"),
            // ResetModeReplaceMode_irm => write!(f, "[4l"),
            // ResetModeNormalLinefeed_lnm => write!(f, "[20l"),
            InsertLines { n } => write!(f, "[{}L", n),
            SelectGraphicRendition => write!(f, "[m"),
            DeleteLines { n } => write!(f, "[{}M", n),
            DeviceStatusReportReady => write!(f, "[0n"),
            DeviceStatusReportStatusReport => write!(f, "[5n"),
            DeviceStatusReportReportCursorPos => write!(f, "[6n"),
            DeviceStatusReportReportCursorPosResponse => write!(f, "[Rn"),
            EraseInFieldFromCursorToEndOfField => write!(f, "[0N"),
            EraseInFieldFromBeginningOfFieldToCursor => write!(f, "[1N"),
            EraseInFieldEntireField => write!(f, "[2N"),
            // DefineAreaQualificationUnprotected => write!(f, "[0o"),
            // DefineAreaQualificationGuarded_PROTECTED => write!(f, "[1o"),
            // DefineAreaQualificationGraphicCharInput => write!(f, "[2o"),
            // DefineAreaQualificationNumericInput => write!(f, "[3o"),
            // DefineAreaQualificationAlphabeticInput => write!(f, "[4o"),
            // DefineAreaQualificationInputJustifiedRight => write!(f, "[5o"),
            // DefineAreaQualificationFillWithZeros => write!(f, "[6o"),
            // DefineAreaQualificationSetHorizontalTab => write!(f, "[7o"),
            // DefineAreaQualificationProtected_UNGUARDED => write!(f, "[8o"),
            // DefineAreaQualificationFillWithSpaces => write!(f, "[9o"),
            EraseInAreaFromCursorToEndOfArea => write!(f, "[0O"),
            EraseInAreaFromBeginningOfAreaToCursor => write!(f, "[1O"),
            EraseInAreaEntireArea => write!(f, "[2O"),
            DeleteCharacters { n } => write!(f, "[{}P", n),
            LoadlEDsTurnOffAlllEDs => write!(f, "[0q"),
            LoadlEDsTurnOnlED1 => write!(f, "[1q"),
            LoadlEDsTurnOnlED2 => write!(f, "[2q"),
            LoadlEDsTurnOnlED3 => write!(f, "[3q"),
            LoadlEDsTurnOnlED4 => write!(f, "[4q"),
            SelectEditingExtentEntireBuffer => write!(f, "[0Q"),
            SelectEditingExtentActiveLine => write!(f, "[1Q"),
            SelectEditingExtentBetweenHorizontalTabs => write!(f, "[2Q"),
            SelectEditingExtentQualifiedArea => write!(f, "[3Q"),
            SetScrollingRegion { top, bottom } => write!(f, "[{};{}r", top, bottom),
            CursorPosReport { row, col } => write!(f, "[{};{}R", row, col),
            SaveCursorPos => write!(f, "[s"),
            // ScrollUp_PAN_DOWN => write!(f, "[<rows>S"),
            WindowManipulation => write!(f, "[t"),
            // ScrollDown_PAN_UP => write!(f, "[<rows>T"),
            RestoreCursorPos => write!(f, "[u"),
            NextPage { n } => write!(f, "[{}U", n),
            PrecedingPage { n } => write!(f, "[{}V", n),
            CursorTabControlSetHorizontalTabAtActivePos => write!(f, "[0W"),
            CursorTabControlSetVerticalTabAtActiveLine => write!(f, "[1W"),
            CursorTabControlClearHorizontalTabAtActivePos => write!(f, "[2W"),
            CursorTabControlClearVerticalTabAtActiveLine => write!(f, "[3W"),
            CursorTabControlClearAllHorizontalTabsAtActiveLine => write!(f, "[4W"),
            CursorTabControlClearAllHorizontalTabs => write!(f, "[5W"),
            CursorTabControlClearAllVerticalTabs => write!(f, "[6W"),
            RequestTerminalParameters => write!(f, "[x"),
            EraseCharacters { n } => write!(f, "[{}X", n),
            TestDiagnosticData => write!(f, "[y"),
            CursorVerticalTabulation { n } => write!(f, "[{}Y", n),
            CursorBackwardTabulation { n } => write!(f, "[{}Z", n),
            EnableCursorKeyToApplication => write!(f, "[?1h"),
            DisableCursorKeyToApplication => write!(f, "[?1l"),
            EnableaNSIMode => write!(f, "[?2h"),
            DisableaNSIMode => write!(f, "[?2l"),
            EnableNumberOfColumnsTo132 => write!(f, "[?3h"),
            DisableNumberOfColumnsTo132 => write!(f, "[?3l"),
            EnableSmoothScrolling => write!(f, "[?4h"),
            DisableSmoothScrolling => write!(f, "[?4l"),
            EnableScreenModeToReverseVideo => write!(f, "[?5h"),
            DisableScreenModeToReverseVideo => write!(f, "[?5l"),
            EnableOriginModeToRelative => write!(f, "[?6h"),
            DisableOriginModeToRelative => write!(f, "[?6l"),
            EnableAutoWrapMode => write!(f, "[?7h"),
            DisableAutoWrapMode => write!(f, "[?7l"),
            EnableAutoRepeatKeys => write!(f, "[?8h"),
            DisableAutoRepeatKeys => write!(f, "[?8l"),
            EnableInterlaceMode => write!(f, "[?9h"),
            DisableInterlaceMode => write!(f, "[?9l"),
            EnableShowToolbar => write!(f, "[?10h"),
            DisableShowToolbar => write!(f, "[?10l"),
            EnableBlinkingCursor => write!(f, "[?12h"),
            DisableBlinkingCursor => write!(f, "[?12l"),
            EnablePrintFeedForm => write!(f, "[?18h"),
            DisablePrintFeedForm => write!(f, "[?18l"),
            EnablePrintExtent => write!(f, "[?19h"),
            DisablePrintExtent => write!(f, "[?19l"),
            EnableShowCursor => write!(f, "[?25h"),
            DisableShowCursor => write!(f, "[?25l"),
            EnableShowScrollbar => write!(f, "[?30h"),
            DisableShowScrollbar => write!(f, "[?30l"),
            EnableEnableFontShifting => write!(f, "[?35h"),
            DisableEnableFontShifting => write!(f, "[?35l"),
            EnableEntertektronixMode => write!(f, "[?38h"),
            DisableEntertektronixMode => write!(f, "[?38l"),
            // EnableAllow80>132_COLUMN_MODE => write!(f,"[?40h"),
            // DisableAllow80>132_COLUMN_MODE => write!(f,"[?40l"),
            // EnableMore(1)_FIX => write!(f,"[?41h"),
            // DisableMore(1)_FIX => write!(f,"[?41l"),
            EnableNationalOrMultinationalCharMode => write!(f, "[?42h"),
            DisableNationalOrMultinationalCharMode => write!(f, "[?42l"),
            EnableMarginBell => write!(f, "[?44h"),
            DisableMarginBell => write!(f, "[?44l"),
            EnableReverseWraparoundMode => write!(f, "[?45h"),
            DisableReverseWraparoundMode => write!(f, "[?45l"),
            EnableStartLogging => write!(f, "[?46h"),
            DisableStartLogging => write!(f, "[?46l"),
            EnableAlternateScreenBuffer => write!(f, "[?47h"),
            DisableAlternateScreenBuffer => write!(f, "[?47l"),
            EnableApplicationKeypadMode => write!(f, "[?66h"),
            DisableApplicationKeypadMode => write!(f, "[?66l"),
            EnableBackarrowSendsBackspace => write!(f, "[?67h"),
            DisableBackarrowSendsBackspace => write!(f, "[?67l"),
            EnableVerticalSplitScreenMode => write!(f, "[?69h"),
            DisableVerticalSplitScreenMode => write!(f, "[?69l"),
            // EnableDon'T_CLEAR_SCREEN_ON_deccolm => write!(f,"[?95h"),
            // DisableDon'T_CLEAR_SCREEN_ON_deccolm => write!(f,"[?95l"),
            EnablevT200MouseReporting => write!(f, "[?1000h"),
            DisablevT200MouseReporting => write!(f, "[?1000l"),
            Enablex11MouseReporting => write!(f, "[?1001h"),
            Disablex11MouseReporting => write!(f, "[?1001l"),
            EnableButtonEventMouseReporting => write!(f, "[?1002h"),
            DisableButtonEventMouseReporting => write!(f, "[?1002l"),
            EnableAnyEventMouseReporting => write!(f, "[?1003h"),
            DisableAnyEventMouseReporting => write!(f, "[?1003l"),
            EnableFocusInOrOutEvents => write!(f, "[?1004h"),
            DisableFocusInOrOutEvents => write!(f, "[?1004l"),
            EnableuTF8MouseMode => write!(f, "[?1005h"),
            DisableuTF8MouseMode => write!(f, "[?1005l"),
            EnablesGRMouseMode => write!(f, "[?1006h"),
            DisablesGRMouseMode => write!(f, "[?1006l"),
            EnableAlternateScrollMode => write!(f, "[?1007h"),
            DisableAlternateScrollMode => write!(f, "[?1007l"),
            EnableScrollToBottomOnTtyOutput => write!(f, "[?1010h"),
            DisableScrollToBottomOnTtyOutput => write!(f, "[?1010l"),
            EnableScrollToBottomOnKeypress => write!(f, "[?1011h"),
            DisableScrollToBottomOnKeypress => write!(f, "[?1011l"),
            EnableUsecLIPBOARDForSpecialPaste => write!(f, "[?1014h"),
            DisableUsecLIPBOARDForSpecialPaste => write!(f, "[?1014l"),
            EnableUrxvtMouseMode => write!(f, "[?1015h"),
            DisableUrxvtMouseMode => write!(f, "[?1015l"),
            // EnablesGRMousePixelMode => write!(f, "[?1016h"),
            // DisablesGRMousePixelMode => write!(f, "[?1016l"),
            // EnablesGRMousePixelMode => write!(f, "[?1016h"),
            // DisablesGRMousePixelMode => write!(f, "[?1016l"),
            EnableBoldKeySendsdEL => write!(f, "[?1021h"),
            DisableBoldKeySendsdEL => write!(f, "[?1021l"),
            EnablesunFunctionKeyMode => write!(f, "[?1022h"),
            DisablesunFunctionKeyMode => write!(f, "[?1022l"),
            EnableMetaSendseSC => write!(f, "[?1023h"),
            DisableMetaSendseSC => write!(f, "[?1023l"),
            Enable8BitMetaKey => write!(f, "[?1034h"),
            Disable8BitMetaKey => write!(f, "[?1034l"),
            EnableNumericKeypadMetaKey => write!(f, "[?1035h"),
            DisableNumericKeypadMetaKey => write!(f, "[?1035l"),
            EnableAlternateKeyModifiers => write!(f, "[?1036h"),
            DisableAlternateKeyModifiers => write!(f, "[?1036l"),
            EnableDeleteKeyToSenddEL => write!(f, "[?1037h"),
            DisableDeleteKeyToSenddEL => write!(f, "[?1037l"),
            EnablealtKeyMode => write!(f, "[?1038h"),
            DisablealtKeyMode => write!(f, "[?1038l"),
            EnableAlternateBackspace => write!(f, "[?1039h"),
            DisableAlternateBackspace => write!(f, "[?1039l"),
            EnablealtSendseSCPrefix => write!(f, "[?1039h"),
            DisablealtSendseSCPrefix => write!(f, "[?1039l"),
            EnableKeepSelectionEvenIfNotHighlighted => write!(f, "[?1040h"),
            DisableKeepSelectionEvenIfNotHighlighted => write!(f, "[?1040l"),
            EnableUsecLIPBOARDSelection => write!(f, "[?1041h"),
            DisableUsecLIPBOARDSelection => write!(f, "[?1041l"),
            EnableBellToUrgent => write!(f, "[?1042h"),
            DisableBellToUrgent => write!(f, "[?1042l"),
            EnableEnableRaisingWindowOnbEL => write!(f, "[?1043h"),
            DisableEnableRaisingWindowOnbEL => write!(f, "[?1043l"),
            EnableReuseMostRecentDataTocLIPBOARD => write!(f, "[?1044h"),
            DisableReuseMostRecentDataTocLIPBOARD => write!(f, "[?1044l"),
            EnableExtendedReverseWraparoundMode => write!(f, "[?1045h"),
            DisableExtendedReverseWraparoundMode => write!(f, "[?1045l"),
            EnableApplicationCursorKeysMode => write!(f, "[?1046h"),
            DisableApplicationCursorKeysMode => write!(f, "[?1046l"),
            EnableAlternateScreenMode => write!(f, "[?1047h"),
            DisableAlternateScreenMode => write!(f, "[?1047l"),
            EnableExtendedCursorMode => write!(f, "[?1048h"),
            DisableExtendedCursorMode => write!(f, "[?1048l"),
            EnableAlternateScreenBufferCursorSaveOrRestore => write!(f, "[?1049h"),
            DisableAlternateScreenBufferCursorSaveOrRestore => write!(f, "[?1049l"),
            EnableTermcapOrTerminfoSpecialKeys => write!(f, "[?1050h"),
            DisableTermcapOrTerminfoSpecialKeys => write!(f, "[?1050l"),
            EnablesunFunctionKeys => write!(f, "[?1051h"),
            DisablesunFunctionKeys => write!(f, "[?1051l"),
            EnablehPFunctionKeys => write!(f, "[?1052h"),
            DisablehPFunctionKeys => write!(f, "[?1052l"),
            EnablesCOFunctionKeys => write!(f, "[?1053h"),
            DisablesCOFunctionKeys => write!(f, "[?1053l"),
            EnablevT200Highlighting => write!(f, "[?1055h"),
            DisablevT200Highlighting => write!(f, "[?1055l"),
            EnablevT220Highlighting => write!(f, "[?1056h"),
            DisablevT220Highlighting => write!(f, "[?1056l"),
            EnablevT320Highlighting => write!(f, "[?1057h"),
            DisablevT320Highlighting => write!(f, "[?1057l"),
            EnableLegacyXtermKeys => write!(f, "[?1060h"),
            DisableLegacyXtermKeys => write!(f, "[?1060l"),
            EnablevT220Keyboard => write!(f, "[?1061h"),
            DisablevT220Keyboard => write!(f, "[?1061l"),
            EnablevT220FunctionKeys => write!(f, "[?1062h"),
            DisablevT220FunctionKeys => write!(f, "[?1062l"),
            EnableSixKeyFunctionKeys => write!(f, "[?1070h"),
            DisableSixKeyFunctionKeys => write!(f, "[?1070l"),
            EnableBracketedPasteMode => write!(f, "[?2004h"),
            DisableBracketedPasteMode => write!(f, "[?2004l"),
            EnableSynchronizedOutputMode => write!(f, "[?2026h"),
            DisableSynchronizedOutputMode => write!(f, "[?2026l"),
            // PrivateSequence => write!(f, "[<;<params>;<final>"),
            // PrivateSequence => write!(f, "[=;<params>;<final>"),
            // PrivateSequence => write!(f, "[>;<params>;<final>"),
            SetWindowTitleAndIconName { text } => write!(f, "]0;{}ST", text),
            SetIconName { text } => write!(f, "]1;{}ST", text),
            SetWindowTitle { text } => write!(f, "]2;{}ST", text),
            SetxPropertyOnTopLevelWindow => write!(f, "]3ST"),
            SetOrReadPaletteColor { n, color_spec } => write!(f, "]4;{};{}ST", n, color_spec),
            ChangeSpecialColorSpec => write!(f, "]5ST"),
            EnableSpecialColor => write!(f, "]6ST"),
            SetCurrentWorkingDirectory { url } => write!(f, "]7;{}ST", url),
            Hyperlink { params, url } => write!(f, "]8;{};{}ST", params, url),
            // Hyperlink_END => write!(f, "]8ST"),
            SendNotification { message } => write!(f, "]9;{}ST", message),
            SetOrReadTextForegroundColor { color_spec } => write!(f, "]10;{}ST", color_spec),
            SetOrReadTextBackgroundColor { color_spec } => write!(f, "]11;{}ST", color_spec),
            SetOrReadTextCursorColor { color_spec } => write!(f, "]12;{}ST", color_spec),
            ChangeMouseForegroundColor => write!(f, "]13ST"),
            ChangeMouseBackgroundColor => write!(f, "]14ST"),
            ChangetektronixForegroundColor => write!(f, "]15ST"),
            ChangetektronixBackgroundColor => write!(f, "]16ST"),
            ChangeHighlightColor => write!(f, "]17ST"),
            ChangetektronixCursorColor => write!(f, "]18ST"),
            ChangeHighlightForegroundColor => write!(f, "]19ST"),
            SetLogFile => write!(f, "]46ST"),
            SetFont => write!(f, "]50ST"),
            ReservedForEmacsShell => write!(f, "]51ST"),
            ManipulateClipboard { c, data } => write!(f, "]52;{};{}ST", c, data),
            ResetPaletteColor { n } => write!(f, "]104;{}ST", n),
            ResetSpecialColorSpec => write!(f, "]105ST"),
            DisableSpecialColor => write!(f, "]106ST"),
            // ResetDynamicColor => write!(f, "]110ST"),
            // ResetDynamicColor => write!(f, "]111ST"),
            // ResetDynamicColor => write!(f, "]112ST"),
            // ResetDynamicColor => write!(f, "]113ST"),
            // ResetDynamicColor => write!(f, "]114ST"),
            // ResetDynamicColor => write!(f, "]115ST"),
            // ResetDynamicColor => write!(f, "]116ST"),
            // ResetDynamicColor => write!(f, "]117ST"),
            // ResetDynamicColor => write!(f, "]118ST"),
            // ResetDynamicColor => write!(f, "]119ST"),
            // finalTermShellIntegration => write!(f, "]133ST"),
            // SendNotification(RXVT_UNICODE) => write!(f,"]777;notify;<title>;<body>ST"),
            XtermModification { name, value } => write!(f, "]1000;{}={}ST", name, value),
            ITerm2ShellIntegration => write!(f, "]1337ST"),
            Send7Bitc1Controls => write!(f, " F"),
            Send8Bitc1Controls => write!(f, " G"),
            SetaNSIConformanceLevel1 => write!(f, " L"),
            SetaNSIConformanceLevel2 => write!(f, " M"),
            SetaNSIConformanceLevel3 => write!(f, " N"),
            SetaNSIConformanceLevel4 => write!(f, " O"),
            // aPCString => write!(f, "_"),
            // g0SelectSpecialGraphicsSet => write!(f, "(0"),
            // g0SelectAlternaterOMStandardCharSet => write!(f, "(1"),
            // g0SelectAlternaterOMSpecialGraphicsSet => write!(f, "(2"),
            // g0SelectuKCharSet => write!(f, "(A"),
            // g0SelectaSCIICharSet => write!(f, "(B"),
            // g1SelectSpecialGraphicsSet => write!(f, ")0"),
            // g1SelectAlternaterOMStandardCharSet => write!(f, ")1"),
            // g1SelectAlternaterOMSpecialGraphicsSet => write!(f, ")2"),
            // g1SelectuKCharSet => write!(f, ")A"),
            // g1SelectaSCIICharSet => write!(f, ")B"),
            ControlSequenceIntroducer => write!(f, "["),
            OperatingSystemCommand => write!(f, "]"),
            Invokeg2CharSetAsgR => write!(f, "}}"),
            // g2SelectSpecialGraphicsSet => write!(f, "*0"),
            // g2SelectAlternaterOMStandardCharSet => write!(f, "*1"),
            // g2SelectAlternaterOMSpecialGraphicsSet => write!(f, "*2"),
            // g2SelectuKCharSet => write!(f, "*A"),
            // g2SelectaSCIICharSet => write!(f, "*B"),
            StringTerminator => write!(f, "\\"),
            // DoubleHeightLine,_TOP_HALF => write!(f,"#3"),
            // DoubleHeightLine,_BOTTOM_HALF => write!(f,"#4"),
            // SingleWidth,_SINGLE_HEIGHT_CHARACTERS => write!(f,"#5"),
            // DoubleWidth,_SINGLE_HEIGHT_CHARACTERS => write!(f,"#6"),
            ScreenAlignmentPattern => write!(f, "#8"),
            SelectDefaultCharSet => write!(f, "%@"),
            SelectuTF8CharSet => write!(f, "%G"),
            StartOfString => write!(f, "^"),
            // g3SelectSpecialGraphicsSet => write!(f, "+0"),
            // g3SelectAlternaterOMStandardCharSet => write!(f, "+1"),
            // g3SelectAlternaterOMSpecialGraphicsSet => write!(f, "+2"),
            // g3SelectuKCharSet => write!(f, "+A"),
            // g3SelectaSCIICharSet => write!(f, "+B"),
            // vT52Mode => write!(f, "<"),
            ApplicationKeypad => write!(f, "="),
            NormalKeypad => write!(f, ">"),
            Invokeg1CharSetAsgR => write!(f, "~"),
            BackIndex => write!(f, "6"),
            // SaveCursorPos => write!(f, "7"),
            // SaveCursorPos => write!(f, "7"),
            // RestoreCursorPos => write!(f, "8"),
            // RestoreCursorPos => write!(f, "8"),
            ForwardIndex => write!(f, "9"),
            ResetToInitialState => write!(f, "c"),
            // ResetToInitialState => write!(f, "c"),
            Index => write!(f, "D"),
            // Index => write!(f, "D"),
            NextLine => write!(f, "E"),
            // NextLine => write!(f, "E"),
            HorizontalTabSet => write!(f, "H"),
            // HorizontalTabSet => write!(f, "H"),
            VerticalTabSet => write!(f, "K"),
            MemoryLock => write!(f, "l"),
            ReverseIndex => write!(f, "M"),
            // ReverseIndex => write!(f, "M"),
            Invokeg2CharSet => write!(f, "n"),
            SingleShift2 => write!(f, "N"),
            Invokeg3CharSet => write!(f, "o"),
            SingleShift3 => write!(f, "O"),
            DeviceControlString => write!(f, "P"),
            // PrivacyMessage => write!(f, "X"),
            // IdentifyDevice => write!(f, "Z"),
            // IdentifyDevice => write!(f, "Z"),
        }
    }
}

pub struct EscapeWriter<'a, W: std::io::Write> {
    writer: &'a mut W,
}

impl<'a, W: std::io::Write> EscapeWriter<'a, W> {
    pub fn new(writer: &'a mut W) -> Self {
        EscapeWriter { writer }
    }

    pub fn handle_term_request(&mut self, term_request: &TerminalRequest) -> IoResult<()> {
        self.esc(term_request)
        // self.flush()
    }

    pub fn flush(&mut self) -> IoResult<()> {
        self.writer.flush()
    }

    pub fn print(&mut self, s: &str) -> IoResult<()> {
        write!(self.writer, "{}", s)
    }

    pub fn print_char_entry(&mut self, c: &CharEntry) -> IoResult<()> {
        self.handle_term_request(&TerminalRequest::Reset)?;
        c.apply_props(self)?;
        write!(self.writer, "{}", c.inner_char())
    }

    pub fn print_char(&mut self, c: &char) -> IoResult<()> {
        write!(self.writer, "{}", c)
    }

    pub fn goto_coord(&mut self, coord: &Vec2) -> IoResult<()> {
        write!(self.writer, "\x1B[{};{}H", coord.y() + 1, coord.x() + 1)
    }

    fn esc(&mut self, code: impl std::fmt::Display) -> IoResult<()> {
        write!(self.writer, "\x1B{}", code)
    }
}
